### ISSUE TITLE
memory warning and background kill

### ISSUE THREAD

**Issue by purkylin** [SDWebImage/SDWebImageLottieCoder#2]
1. Memory warning
2. Terminate app when in background

**Comment by dreampiggy** [comment]
@purklin This seems solved by upstream rlottie with v0.1.0 official version. Please have a update.
https://github.com/Samsung/rlottie/releases
https://github.com/SDWebImage/librlottie-Xcode#note

Note: The previous 0.1.0 version have been removed. Because that's a temp commit, use the official 0.1.0 version from Samsung instead.

**Comment by purkylin** [comment]
Thanks , I will close it.
I have switched to another [repo](https://github.com/purkylin/KingSticker)
